const express=require("express");
const app=express();
const cookieParser=require("cookie-parser");
app.use(cookieParser());
const authRouter=require("./routes/auth.route.js");
const postRouter=require("./routes/post.route.js");
const userRouter=require("./routes/user.route.js");
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use("/api/auth",authRouter);
app.use("/api/posts",postRouter);
app.use("/api/users",userRouter);
module.exports=app;