const express=require("express");
const app=express();
const cookieParser=require("cookie-parser");
const authRouter=require("./routes/auth.routes.js");
const postRouter=require("./routes/post.routes.js");
const userRouter=require("./routes/user.route.js");
app.use(cookieParser());
app.use(express.json());
app.use("/api/auth",authRouter);
app.use("/api/posts",postRouter);
app.use("/api/users",userRouter);
module.exports=app;